Université Paris Dauphine - PSL
lovasoa/ophirofox pull request #119
Opened 2023-09-06 10:57 UTC by slin613

2023-09-06 15:53 UTC, lovasoa requested changes

2023-09-06 15:53 UTC, lovasoa commented on ophirofox/manifest.json
> +          "AUTH_URL":"https://passeport.dauphine.fr/cas/login?service=https%3a%2f%2flogin.proxy.bu.dauphine.fr%2flogin%3fqurl%3dezp.2aHR0cHM6Ly9ub3V2ZWF1LmV1cm9wcmVzc2UuY29tL2FjY2Vzcy9pcC9kZWZhdWx0Lm
Le format de l'URL ne me semble pas correct, par rapport aux autres.

L'authentification existante  "Université PSL" ne fonctionne pas ?

2023-09-07 13:14 UTC, lovasoa commented
@slin613 , est-ce que l'intégration existante de PSL ne fonctionne pas chez vous ?

2023-09-07 13:48 UTC, slin613 commented
> @slin613 , est-ce que l'intégration existante de PSL ne fonctionne pas chez vous ?

Si effectivement, je crois qu'elle fonctionne, merci @lovasoa !

2023-09-07 14:38 UTC, closed without merging