Ajouter Université de Rouen
lovasoa/ophirofox pull request #129
Opened 2023-09-09 06:44 UTC by MACHARP2

2023-09-09 16:24 UTC, lovasoa requested changes

2023-09-09 16:24 UTC, lovasoa commented on ophirofox/manifest.json
> +          "AUTH_URL": "https://odin.univ-rouen.fr/view/action/uresolver.do?operation=resolveService&package_service_id=6147803870006061&institutionId=6061&customerId=6060&VE=true"
Est-ce que vous êtes sûr de l'url ? Il n'y en a pas une qui contient `/access/ip/default.aspx` ? Et il faut aussi ajouter l'url du proxy europresse dans la partie optional_permissions

2023-10-25 12:57 UTC, lovasoa commented on ophirofox/manifest.json
> +          "AUTH_URL": "https://odin.univ-rouen.fr/view/action/uresolver.do?operation=resolveService&package_service_id=6147803870006061&institutionId=6061&customerId=6060&VE=true"
@MACHARP2 , des nouvelles ?

2024-09-10 16:44 UTC, Write commented
Je clos car complété ici : https://github.com/lovasoa/ophirofox/pull/258

2024-09-10 16:44 UTC, closed without merging