feat: add lesechos.fr
lovasoa/ophirofox pull request #14
Opened 2022-10-08 22:56 UTC by RaitoBezarius

This adds a basic support for lesechos.fr ; I plan to maintain it as my SO is using a lot lesechos.fr, let me know if you need me to do more changes for it to be accepted.

2022-10-10 17:40 UTC, lovasoa requested changes
Je l'ai testé un peu, mais malheureusement le site des echos a l'air plus compliqué à prendre en charge, parce qu'il fait beaucoup de client-side rendering. Dans l'état actuel, le bouton "lire sur europresse" disparaît parfois après le chargement complet de la page, et n'apparaît plus après une navigation interne d'un article à un autre sur le site...

2022-10-10 17:42 UTC, RaitoBezarius commented
Hmm, je resterais avec tes suggestions et je regarderais quel event je peux
écouter pour injecter au moment opportun.
Je pense que c'est pas trop infaisable.
Merci pour ton test !

Le lun. 10 oct. 2022 à 19:41, Ophir LOJKINE ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
>
> Je l'ai testé un peu, mais malheureusement le site des echos a l'air plus
> compliqué à prendre en charge, parce qu'il fait beaucoup de client-side
> rendering. Dans l'état actuel, le bouton "lire sur europresse" disparaît
> parfois après le chargement complet de la page, et n'apparaît plus après
> une navigation interne d'un article à un autre sur le site...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lovasoa/ophirofox/pull/14#pullrequestreview-1136356204>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACMZRAGXTGOGHCZE33G6J3WCRILNANCNFSM6AAAAAARAN4VJE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-20 06:00 UTC, Write commented
Pour détecter le changement d'URI, pour le moment  j'ai trouvé 

```
// store url on load
let currentPage = location.href;

// listen for changes
setInterval(function()
{
    if (currentPage != location.href)
    {
        // page has changed, set new page as 'current'
        currentPage = location.href;
        alert('changé pour: ' + location.href)
    }
}, 500);
```

J'ai utilisé alert() car ils override la fonction console.log()

2024-01-21 00:04 UTC, lovasoa commented
Wow, c'est à éviter ça. On ne va pas faire tourner du code en boucle 2 fois par seconde pour rien.

Si on veut vraiment détecter juste les changements d'url, on peut monkey-patcher `window.history.pushState`, pour intercepter les appels.

2024-01-21 00:11 UTC, Write commented
> Wow, c'est à éviter ça. On ne va pas faire tourner du code en boucle 2 fois par seconde pour rien.
> 
> Si on veut vraiment détecter juste les changements d'url, on peut monkey-patcher `window.history.pushState`, pour intercepter les appels.

Oui en effet,

```
        // Monkey patching window.history 
        (function(history) { 
            var pushState = history.pushState; 
            history.pushState = function(state) { 
                if (typeof history.onpushstate == "function") 
                { 
                    history.onpushstate({ 
                        state: state 
                    }); 
                } 
                return pushState.apply(history, arguments); 
            } 
        })(window.history); 
        window.onpopstate = history.onpushstate = function(e) 
        { 
            alert('History has been modified!') 
        }; 
```

Source : https://www.geeksforgeeks.org/how-to-get-history-changes-notification-via-history-pushstate-method/

2024-01-26 13:55 UTC, Write commented
Ajout des échos fait dans le merge : #190

2024-01-26 15:02 UTC, closed without merging