Update manifest.json
lovasoa/ophirofox pull request #155
Opened 2023-10-06 13:17 UTC by SCDReunion

, "https://nouveau-europresse-com.elgebar.univ-reunion.fr/*"

2023-10-06 15:48 UTC, lovasoa requested changes

2023-10-06 15:48 UTC, lovasoa commented on ophirofox/manifest.json
> +    , "https://nouveau.europresse.com.elgebar.univ-reunion.fr/*"
Il ne suffit pas de rajouter cette ligne, il faut aussi compléter la section ophirofox_metadata plus bas avec votre URL de connection

2023-10-10 12:21 UTC, lovasoa commented on ophirofox/manifest.json
> +    , "https://nouveau.europresse.com.elgebar.univ-reunion.fr/*"
@SCDReunion

2023-10-24 12:10 UTC, SCDReunion commented on ophirofox/manifest.json
>    "background": {
"name": "Université de La Réunion",
          "AUTH_URL": "https://elgebar.univ-reunion.fr/login?url=https://nouveau.europresse.com/access/ip/default.aspx?un=BUREUNIONT_1"

2023-10-24 14:11 UTC, merged