Update manifest.json
lovasoa/ophirofox pull request #173
Opened 2023-11-07 11:05 UTC by MCO01ES

Ajouter ESSEC merci

2023-11-07 13:31 UTC, lovasoa requested changes

2023-11-07 13:31 UTC, lovasoa commented on ophirofox/manifest.json
> +          "AUTH_URL": "https://nouveau-europresse-com.essec.idm.oclc.org/Search/Reading"
Je pense que cette url n'est pas correcte. Il faut faut qqch qui ressemble à ça:

```
https://essec.idm.oclc.org/login?url=https://nouveau.europresse.com/access/ip/default.aspx?un=UN_CODE_ICI
```

C'est l'url générale de connection à la plateforme qu'on a dû vous donner, il faut bien mettre l'url originale et pas la cible vers laquelle elle redirige.

2023-11-07 15:33 UTC, MCO01ES commented on ophirofox/manifest.json
> +          "AUTH_URL": "https://nouveau-europresse-com.essec.idm.oclc.org/Search/Reading"
Merci j'ai refait une pull request avec la bonne url

2023-11-07 16:31 UTC, lovasoa commented
fermé en faveur de https://github.com/lovasoa/ophirofox/pull/175

@MCO01ES : pour la prochaine fois: pas besoin d'ouvrir deux PR, vous pouvez juste mettre à jour le code sur votre branche, et la pr se met à jour toute seule :wink:

2023-11-07 16:31 UTC, closed without merging

2023-11-08 08:54 UTC, MCO01ES commented
merci je débute avec GitHub
l'extension ne fonctinne pas sur Chrome pour l'instant
je teste avec Firefox

[image: ESSEC Business School] <http://www.essec.fr/>

Mathilde COCHEREL
*Case Publishing and Research Help Coordinator*
K-Lab
<http://learningcenter.essec.edu/broadcast-and-publish-your-pedagogical-contents>
 *ESSEC Business School*
3 Avenue Bernard Hirsch, 95021 Cergy-Pontoise Cedex
• Tel: + 33 (0) 1 34 43 32 78 // Office: B126
• Web: www.essec.fr <https://www.essec.edu/fr/> // www.essec.edu
<https://www.essec.edu/en/>
[image: LinkedIn ESSEC Business School]
<https://www.linkedin.com/company/essec-business-school> [image: X ESSEC
Business School] <https://twitter.com/essec> [image: Instagram ESSEC
Business School] <https://instagram.com/essecbs/> [image: Facebook ESSEC
Business School] <https://www.facebook.com/essec> [image: Youtube ESSEC
Business School] <https://www.youtube.com/user/essec> [image: Sauveteur
Secouriste du Travail]


Le mar. 7 nov. 2023 à 17:31, Ophir LOJKINE ***@***.***> a
écrit :

> fermé en faveur de #175
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lovasoa_ophirofox_pull_175&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=Yobg4cf4bM8fqM8KIju_UnXWdKm1bCW_hmUWhaxUoeleuumnHx-G1GmMImUZPQXw&s=QRqM1fKd6G0eo-B7S9X7F_7QoqBFQ01sSMcSRsIhD4Q&e=>
>
> @MCO01ES
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MCO01ES&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=Yobg4cf4bM8fqM8KIju_UnXWdKm1bCW_hmUWhaxUoeleuumnHx-G1GmMImUZPQXw&s=WG5ZPaELQW3fb31wJBLEvlFOzD2b5h51hRXTYHDpH8w&e=>
> : pour la prochaine fois: pas besoin d'ouvrir deux PR, vous pouvez juste
> mettre à jour le code sur votre branche, et la pr se met à jour toute seule
> 😉
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lovasoa_ophirofox_pull_173-23issuecomment-2D1799127026&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=Yobg4cf4bM8fqM8KIju_UnXWdKm1bCW_hmUWhaxUoeleuumnHx-G1GmMImUZPQXw&s=SKIf43XqllIniTY-PWolDi9germE2IT58h9LrHCu8U0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BDZOD4NO6PPKTULH6LUXQODYDJO65AVCNFSM6AAAAAA7A7VPH6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJZGEZDOMBSGY&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=Yobg4cf4bM8fqM8KIju_UnXWdKm1bCW_hmUWhaxUoeleuumnHx-G1GmMImUZPQXw&s=5nBTsLXv7vcXpPT8m5zQ2zjiR7Rdg-HzYq-2lZaUejg&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-08 08:59 UTC, MCO01ES commented
excusez-moi c'est peut-être parce que j'avais installé l'extention sur
chrome avant d'ajouter l'ESSEC...que je ne trouve pas dans la liste des
partenaires dans les options de l'extention déjà installée : je vais
desinstaller / reinstaller l'extension sur chrome et tester à  neuf sur
firefox
merci, je vous tiens au courant

[image: ESSEC Business School] <http://www.essec.fr/>

Mathilde COCHEREL
*Case Publishing and Research Help Coordinator*
K-Lab
<http://learningcenter.essec.edu/broadcast-and-publish-your-pedagogical-contents>
 *ESSEC Business School*
3 Avenue Bernard Hirsch, 95021 Cergy-Pontoise Cedex
• Tel: + 33 (0) 1 34 43 32 78 // Office: B126
• Web: www.essec.fr <https://www.essec.edu/fr/> // www.essec.edu
<https://www.essec.edu/en/>
[image: LinkedIn ESSEC Business School]
<https://www.linkedin.com/company/essec-business-school> [image: X ESSEC
Business School] <https://twitter.com/essec> [image: Instagram ESSEC
Business School] <https://instagram.com/essecbs/> [image: Facebook ESSEC
Business School] <https://www.facebook.com/essec> [image: Youtube ESSEC
Business School] <https://www.youtube.com/user/essec> [image: Sauveteur
Secouriste du Travail]


Le mer. 8 nov. 2023 à 09:54, COCHEREL, Mathilde ***@***.***> a
écrit :

> merci je débute avec GitHub
> l'extension ne fonctinne pas sur Chrome pour l'instant
> je teste avec Firefox
>
> [image: ESSEC Business School] <http://www.essec.fr/>
>
> Mathilde COCHEREL
> *Case Publishing and Research Help Coordinator*
> K-Lab
> <http://learningcenter.essec.edu/broadcast-and-publish-your-pedagogical-contents>
>  *ESSEC Business School*
> 3 Avenue Bernard Hirsch, 95021 Cergy-Pontoise Cedex
> • Tel: + 33 (0) 1 34 43 32 78 // Office: B126
> • Web: www.essec.fr <https://www.essec.edu/fr/> // www.essec.edu
> <https://www.essec.edu/en/>
> [image: LinkedIn ESSEC Business School]
> <https://www.linkedin.com/company/essec-business-school> [image: X ESSEC
> Business School] <https://twitter.com/essec> [image: Instagram ESSEC
> Business School] <https://instagram.com/essecbs/> [image: Facebook ESSEC
> Business School] <https://www.facebook.com/essec> [image: Youtube ESSEC
> Business School] <https://www.youtube.com/user/essec> [image: Sauveteur
> Secouriste du Travail]
>
>
> Le mar. 7 nov. 2023 à 17:31, Ophir LOJKINE ***@***.***> a
> écrit :
>
>> fermé en faveur de #175
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lovasoa_ophirofox_pull_175&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=Yobg4cf4bM8fqM8KIju_UnXWdKm1bCW_hmUWhaxUoeleuumnHx-G1GmMImUZPQXw&s=QRqM1fKd6G0eo-B7S9X7F_7QoqBFQ01sSMcSRsIhD4Q&e=>
>>
>> @MCO01ES
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MCO01ES&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=Yobg4cf4bM8fqM8KIju_UnXWdKm1bCW_hmUWhaxUoeleuumnHx-G1GmMImUZPQXw&s=WG5ZPaELQW3fb31wJBLEvlFOzD2b5h51hRXTYHDpH8w&e=>
>> : pour la prochaine fois: pas besoin d'ouvrir deux PR, vous pouvez juste
>> mettre à jour le code sur votre branche, et la pr se met à jour toute seule
>> 😉
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lovasoa_ophirofox_pull_173-23issuecomment-2D1799127026&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=Yobg4cf4bM8fqM8KIju_UnXWdKm1bCW_hmUWhaxUoeleuumnHx-G1GmMImUZPQXw&s=SKIf43XqllIniTY-PWolDi9germE2IT58h9LrHCu8U0&e=>,
>> or unsubscribe
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BDZOD4NO6PPKTULH6LUXQODYDJO65AVCNFSM6AAAAAA7A7VPH6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJZGEZDOMBSGY&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=Yobg4cf4bM8fqM8KIju_UnXWdKm1bCW_hmUWhaxUoeleuumnHx-G1GmMImUZPQXw&s=5nBTsLXv7vcXpPT8m5zQ2zjiR7Rdg-HzYq-2lZaUejg&e=>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2023-11-08 09:02 UTC, lovasoa commented
la nouvelle version n'est pas encore publiée sur Chrome

2023-11-08 09:06 UTC, MCO01ES commented
oui jai fait toutes les manips habituelles et je ne vois toujours pas
l'ESSEC
par contre ça marche très  bien sur firefox
savez-vous quand la mise à jour sera publiée sur chrome ?
merci

[image: ESSEC Business School] <http://www.essec.fr/>

Mathilde COCHEREL
*Case Publishing and Research Help Coordinator*
K-Lab
<http://learningcenter.essec.edu/broadcast-and-publish-your-pedagogical-contents>
 *ESSEC Business School*
3 Avenue Bernard Hirsch, 95021 Cergy-Pontoise Cedex
• Tel: + 33 (0) 1 34 43 32 78 // Office: B126
• Web: www.essec.fr <https://www.essec.edu/fr/> // www.essec.edu
<https://www.essec.edu/en/>
[image: LinkedIn ESSEC Business School]
<https://www.linkedin.com/company/essec-business-school> [image: X ESSEC
Business School] <https://twitter.com/essec> [image: Instagram ESSEC
Business School] <https://instagram.com/essecbs/> [image: Facebook ESSEC
Business School] <https://www.facebook.com/essec> [image: Youtube ESSEC
Business School] <https://www.youtube.com/user/essec> [image: Sauveteur
Secouriste du Travail]


Le mer. 8 nov. 2023 à 10:02, Ophir LOJKINE ***@***.***> a
écrit :

> la nouvelle version n'est pas encore publiée sur Chrome
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lovasoa_ophirofox_pull_173-23issuecomment-2D1801361027&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=n_5PN6gboh4Mi-hgAcZJ5nY-pOEwZJrS-Ptbg3b7Wm8de0sR4KEdz0JRmyuSCXXz&s=Tt7Od1RNbaGqz5P5h_jFMcRXfFuwDBOhu1EsdU4vseE&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BDZOD4KXQSNSRHL53XFZP4LYDNDDHAVCNFSM6AAAAAA7A7VPH6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBRGM3DCMBSG4&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=n_5PN6gboh4Mi-hgAcZJ5nY-pOEwZJrS-Ptbg3b7Wm8de0sR4KEdz0JRmyuSCXXz&s=GztFP1GXkld_1PF0TeFdKVpd32NkH7rR1r2wfGxdOO8&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-08 18:30 UTC, lovasoa commented
Le processus est manuel, et il y a un délai pour l'acceptation par Google, donc j'attends d'avoir plusieurs changements pour les soumettre en même temps à Google.

2023-11-15 09:08 UTC, MCO01ES commented
merci beaucoup
ça fonctionne bien sur firefox et chrome maintenant
prévoyez-vous d'autres navigateurs, ou une appli smartphone ?

[image: ESSEC Business School] <http://www.essec.fr/>

Mathilde COCHEREL
*Case Publishing and Research Help Coordinator*
K-Lab
<http://learningcenter.essec.edu/broadcast-and-publish-your-pedagogical-contents>
 *ESSEC Business School*
3 Avenue Bernard Hirsch, 95021 Cergy-Pontoise Cedex
• Tel: + 33 (0) 1 34 43 32 78 // Office: B126
• Web: www.essec.fr <https://www.essec.edu/fr/> // www.essec.edu
<https://www.essec.edu/en/>
[image: LinkedIn ESSEC Business School]
<https://www.linkedin.com/company/essec-business-school> [image: X ESSEC
Business School] <https://twitter.com/essec> [image: Instagram ESSEC
Business School] <https://instagram.com/essecbs/> [image: Facebook ESSEC
Business School] <https://www.facebook.com/essec> [image: Youtube ESSEC
Business School] <https://www.youtube.com/user/essec> [image: Sauveteur
Secouriste du Travail]


Le mer. 8 nov. 2023 à 19:30, Ophir LOJKINE ***@***.***> a
écrit :

> Le processus est manuel, et il y a un délai pour l'acceptation par Google,
> donc j'attends d'avoir plusieurs changements pour les soumettre en même
> temps à Google.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lovasoa_ophirofox_pull_173-23issuecomment-2D1802432853&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=ECKr_0FgvhyQLKH3F_G4Nk2IxydSyKgRJpjGcqM8AlAhHm1mWuWDBNM6ov0_QYKv&s=A9RsBDcKcvqg9xJd14GSngnm0uLumu9m_Pu35UsZbU4&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BDZOD4NTE47WZY5VURPTEPDYDPFUJAVCNFSM6AAAAAA7A7VPH6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBSGQZTEOBVGM&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=ECKr_0FgvhyQLKH3F_G4Nk2IxydSyKgRJpjGcqM8AlAhHm1mWuWDBNM6ov0_QYKv&s=RJpKURwN0usYdjhP5TizLzUW2k5M2Du7Fgpa8Dew3Lc&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-15 09:10 UTC, lovasoa commented
À propos des smartphones, vous pouvez lire cette discussion: https://github.com/lovasoa/ophirofox/issues/139

2023-11-15 09:11 UTC, lovasoa commented
Et à propos de Safari: https://github.com/lovasoa/ophirofox/issues/131

2023-11-15 09:12 UTC, lovasoa commented
Si quelqu'un veut faire un don de 100$/an, je suis prêt à faire le travail, et packager l'extension pour la distribuer sur safari.

2023-11-15 09:55 UTC, MCO01ES commented
merci infiniment
je vois pour le don et reviens vers vous

[image: ESSEC Business School] <http://www.essec.fr/>

Mathilde COCHEREL
*Case Publishing and Research Help Coordinator*
K-Lab
<http://learningcenter.essec.edu/broadcast-and-publish-your-pedagogical-contents>
 *ESSEC Business School*
3 Avenue Bernard Hirsch, 95021 Cergy-Pontoise Cedex
• Tel: + 33 (0) 1 34 43 32 78 // Office: B126
• Web: www.essec.fr <https://www.essec.edu/fr/> // www.essec.edu
<https://www.essec.edu/en/>
[image: LinkedIn ESSEC Business School]
<https://www.linkedin.com/company/essec-business-school> [image: X ESSEC
Business School] <https://twitter.com/essec> [image: Instagram ESSEC
Business School] <https://instagram.com/essecbs/> [image: Facebook ESSEC
Business School] <https://www.facebook.com/essec> [image: Youtube ESSEC
Business School] <https://www.youtube.com/user/essec> [image: Sauveteur
Secouriste du Travail]


Le mer. 15 nov. 2023 à 10:12, Ophir LOJKINE ***@***.***> a
écrit :

> Si quelqu'un veut faire un don de 100$/an, je suis prêt à faire le
> travail, et packager l'extension pour la distribuer sur safari.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lovasoa_ophirofox_pull_173-23issuecomment-2D1812067166&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=NqWzyZ5QC9tIuuKCJvOWY4-JRDGBwTka2qF6AJRAdWQhVSFwqvzyt2zMm20QAA8w&s=NJ8_41f_sRv69aWIvfBUPwige0MTRRHhiYH_JnGooFg&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BDZOD4IHXVLH6OA3CKSSRRTYESBPFAVCNFSM6AAAAAA7A7VPH6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJSGA3DOMJWGY&d=DwMFaQ&c=oS_0xOYps7FNW56RWijYeQ&r=d6TzMjz20JEHpiLf3OtllCzCQJrcYggZ5uiO8yk5RtI&m=NqWzyZ5QC9tIuuKCJvOWY4-JRDGBwTka2qF6AJRAdWQhVSFwqvzyt2zMm20QAA8w&s=mShR2kvAztlOx-4_WQVrqCMqw2lOdfk5KBVxVm9Fe5U&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>