Update manifest.json
lovasoa/ophirofox pull request #189
Opened 2024-01-23 08:51 UTC by lbaudin

Accès pour les écoles du GENES, i.e. ENSAE/ENSAI, cf. https://genes.bibli.fr/index.php?lvl=cmspage&pageid=14&id_rubrique=70

2024-01-23 14:50 UTC, lovasoa requested changes
Il manque l'url du proxy europresse à ajouter dans optional_permissions

2024-01-23 17:01 UTC, lbaudin commented
> Il manque l'url du proxy europresse à ajouter dans optional_permissions

Nous n'avons pas de proxy (à la différence des autres établissements que j'ai fréquenté), tout comme par exemple l'ENSTA. Cela ne fonctionne que sur le réseau interne. Pour l'externe il y a un mécanisme avec un httpref mais je crois qu'il n'y a pas l'équivalent  implémenté dans ophirofox, donc ce n'est pas possible.

2024-01-23 21:28 UTC, lovasoa commented
Comment fonctionne le mécanisme avec un httpref ? N'est-ce pas une identification spécifique à l'établissement qui redirige ensuite vers europresse?

2024-01-24 09:17 UTC, lbaudin commented
Ma compréhension du mécanisme est que, en exetrne, si le lien est ouvert depuis le site de la bibliothèque (qui est donc en http referer), alors la connexion s'établie (sans proxy), dans une limite de 2 utilisateurs simultanés (?). Si le lien est utilisé directement (sans referer), alors la connexion échoue. Ça me semble peu robuste, ça ne peut marcher que pour les très petits établissements…

2024-01-24 20:32 UTC, lovasoa commented
Et surtout, n'importe qui, sans aucun lien avec l'établissement, peut se connecter sans payer juste en envoyant le bon referer.

2024-01-24 20:32 UTC, merged