✨ Introduce the support of article published time
lovasoa/ophirofox pull request #192
Opened 2024-01-26 06:25 UTC by lnoss

… to improve Europresse engine search time.

Je n'ai pas essayé mes modifications faute de savoir comment tu compiles tout.

2024-01-26 07:39 UTC, lnoss commented
À terme, l'objectif pourrait être aussi de trier par contenu, mais je ne sais pas si l'identifiant des sources de presse sont stables. Recherche plus rapide et moins de CO2.

2024-01-26 09:04 UTC, lovasoa commented
Pour tester l'extension, il n'y a aucune compilation particulière à faire. Chargez là simplement dans votre navigateur. Si tout fonctionne comme vous le voulez, alors c'est bon!

Vérifiez bien sur tous les journaux supportés qu'aucun n'utilise une meta avec une date de publication qui n'est pas compatible avec les données enregistrées sur Europresse.

2024-01-26 09:16 UTC, lnoss commented
Ah oui, il faudrait peut-être préciser pour les contributeurs que la pipeline génère un artefact avec l'extension... Je vais essayer plusieurs cas dans la journée, cela semble marcher au premier coup d'œil.

Quel travail désirable à l’horizon 2050 ? Publié le 24 janvier 2024 à 06h00 par Anne Rodier. https://www.lemonde.fr/emploi/article/2024/01/24/quel-travail-desirable-a-l-horizon-2050_6212645_1698637.html
![image](https://github.com/lovasoa/ophirofox/assets/74484200/eb26b7eb-75b0-4c78-b751-2a45e74feadb)

2024-01-26 09:17 UTC, lnoss commented
D'ailleurs, victime en direct de #25.

2024-01-28 01:31 UTC, lnoss commented
Cela devrait être bon, maintenant. J'ai rencontré un cas où _Depuis 3 jours_ n'affichait pas un article publiait il y a moins de trois jours, j'en ai supposé que le moteur de recherche d'Europresse utilise un minuit UTC lors des recherches, même s'ils sauvegardent les dates de publication UTC exactes.

2024-01-28 01:37 UTC, lnoss commented
Je vois un cas potentiellement problématique : je ne sais pas si c'est une période qui exclut ou inclut la borne supérieure.

Il est peut-être possible que consulter exactement trois jours (et tout autre période) après la publication de l'article implique un mauvais choix de période (`<=`). Et bon, vu qu'ils ne précisent pas... 

Soit prendre le temps de tester l'extension pile à la bonne heure, soit passer à des inférieurs stricts.

2024-01-28 12:52 UTC, lovasoa requested changes

2024-01-28 13:02 UTC, lnoss commented on ophirofox/content_scripts/config.js
> +  const metaTags = document.querySelectorAll('meta');
De ce genre ?
```suggestion
( 
document.querySelector("meta[property='article:published_time']") ||
document.querySelector("meta[property='og:article:published_time']") ||
document.querySelector("meta[property='date:published_time']")
)
.getAttribute("content");
```
Je ne sais pas, ça m'est égal personnellement.

2024-01-28 13:06 UTC, lnoss commented on ophirofox/content_scripts/config.js
> +  const metaTags = document.querySelectorAll('meta');
Oh, on peut mélanger les trois d'un coup sinon !
```suggestion
document.querySelector( "meta[property='article:published_time'], meta[property='og:article:published_time'], meta[property='date:published_time']").getAttribute("content");
```

2024-01-28 15:39 UTC, lovasoa commented on ophirofox/content_scripts/config.js
> +  const metaTags = document.querySelectorAll('meta');
Oui, voilà, mais du coup il faut enlever la boucle en dessous, et gérer le cas où le querySelector retourne null

2024-01-29 12:10 UTC, lovasoa approved these changes

2024-01-29 12:10 UTC, merged