Ajout du support pour l'INSA Lyon et compléments
lovasoa/ophirofox pull request #7
Opened 2022-02-25 15:11 UTC by julessanglier

+ support Europresse INSA Lyon
+ suppression du Paywall Le Monde
+ support Monde Diplomatique

2022-02-25 17:37 UTC, lovasoa requested changes
Super ! Merci pour la contribution :+1: 

Est-ce que l'on pourrait juste garder les liens de téléchargement du readme ?

2022-02-25 17:37 UTC, lovasoa commented on README.md
> +Une extension pour navigateurs qui permet de lire les articles du **Monde**, du **Figaro**, de **Libération** et du **Monde Diplomatique** sur son compte **Europresse**.
Pourquoi supprimer les liens de téléchargement de l'extension ?

2022-02-25 17:37 UTC, lovasoa commented on ophirofox/content_scripts/lemonde.js
> +    document.getElementById('js-message-register').remove();
On ne devrait pas plutôt faire ça dans le CSS ? ça a moins de chance de casser le site si un jour un autre script du mode fait référence à l'élément...

2022-02-25 18:57 UTC, julessanglier commented
> Super ! Merci pour la contribution :+1: 
> 
> 
> 
> Est-ce que l'on pourrait juste garder les liens de téléchargement du readme ?

Aucun problème, c'était une erreur !

2022-02-25 22:02 UTC, lovasoa commented
@julessanglier , du coup, vous pouvez corriger la pr ?

2022-03-02 12:23 UTC, lovasoa approved these changes

2022-03-02 12:24 UTC, merged

2022-03-02 12:36 UTC, lovasoa commented
C'est publié ! Merci beaucoup de ma part et de celle de tous les utilisateurs :slightly_smiling_face: